"""Add author_id to News model

Revision ID: 00755d28bbd0
Revises: bc39ef650456
Create Date: 2024-05-23 20:24:36.249897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00755d28bbd0'
down_revision = 'bc39ef650456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_news_timestamp'), ['timestamp'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_news_timestamp'))
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
